'use client';

import React, { useState, useEffect, use } from 'react';
import Link from 'next/link';
import { 
  ArrowLeft, 
  Download, 
  Calendar, 
  Clock, 
  CheckSquare, 
  FileText, 
  AlertTriangle, 
  User, 
  Copy, 
  Search, 
  Check, 
  ShieldAlert, 
  CheckSquare2,
  Square
} from 'lucide-react';
import { Meeting, ActionItem } from '@/lib/db';

interface MeetingPageProps {
  params: Promise<{ id: string }>;
}

export default function MeetingPage({ params }: MeetingPageProps) {
  const { id } = use(params);
  
  const [meeting, setMeeting] = useState<Meeting | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState<'decisions' | 'actions' | 'risks'>('decisions');
  
  // Transcript search and copy
  const [transcriptSearch, setTranscriptSearch] = useState('');
  const [copied, setCopied] = useState(false);

  // Fetch single meeting details
  const fetchMeeting = async () => {
    try {
      const response = await fetch(`/api/meetings/${id}`);
      if (response.ok) {
        const data = await response.json();
        setMeeting(data);
      } else {
        throw new Error('Failed to retrieve meeting details');
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || 'Error occurred');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMeeting();
  }, [id]);

  // Toggle Action Item Status
  const handleToggleAction = async (itemId: string) => {
    if (!meeting || !meeting.analysis) return;

    const updatedActions: ActionItem[] = meeting.analysis.actionItems.map(item => {
      if (item.id === itemId) {
        return { 
          ...item, 
          status: (item.status === 'completed' ? 'pending' : 'completed') as 'pending' | 'completed'
        };
      }
      return item;
    });

    const updatedMeeting = {
      ...meeting,
      analysis: {
        ...meeting.analysis,
        actionItems: updatedActions
      }
    };

    setMeeting(updatedMeeting);

    try {
      const response = await fetch(`/api/meetings/${id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ actionItems: updatedActions }),
      });
      if (!response.ok) {
        throw new Error('Failed to update action item on database');
      }
    } catch (err) {
      console.error(err);
      fetchMeeting();
    }
  };

  // Copy transcript to clipboard
  const handleCopyTranscript = () => {
    if (!meeting) return;
    navigator.clipboard.writeText(meeting.transcript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Export insights as Markdown
  const handleExportMarkdown = () => {
    if (!meeting || !meeting.analysis) return;

    const analysis = meeting.analysis;
    const formattedDate = new Date(meeting.date).toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    });

    const mdContent = `# Meeting Intelligence: ${meeting.title}
Date: ${formattedDate}
Duration: ${meeting.duration}

## 1. Executive Summary
${analysis.summary}

## 2. Decisions Made
${analysis.decisions.map((d, i) => `${i + 1}. **${d.decision}**\n   - Decider: ${d.decider}\n   - Context: ${d.context}`).join('\n\n')}

## 3. Action Items
${analysis.actionItems.map((a, i) => `- [${a.status === 'completed' ? 'x' : ' '}] **${a.task}**\n  - Assignee: ${a.assignee}\n  - Due Date: ${a.dueDate}`).join('\n')}

## 4. Risks & Mitigations
${analysis.risks.map((r, i) => `${i + 1}. **[${r.impact.toUpperCase()}] ${r.risk}**\n   - Mitigation: ${r.mitigation}`).join('\n\n')}

---
Generated by Vocalize Intelligence.
`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${meeting.title.toLowerCase().replace(/\s+/g, '-')}-insights.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center py-20 gap-3 text-zinc-500">
        <div className="w-8 h-8 rounded-full border-2 border-violet-500/20 border-t-violet-500 animate-spin" />
        <p className="text-sm font-medium">Extracting intelligence details...</p>
      </div>
    );
  }

  if (error || !meeting) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-20 text-center">
        <div className="w-16 h-16 bg-rose-500/10 text-rose-400 rounded-2xl flex items-center justify-center mx-auto mb-6 border border-rose-500/15">
          <AlertTriangle className="w-8 h-8" />
        </div>
        <h2 className="text-2xl font-bold font-display text-zinc-200">Meeting report not found</h2>
        <p className="text-zinc-500 mt-2 max-w-md mx-auto">{error || "The requested meeting ID doesn't exist in our database."}</p>
        <Link href="/dashboard" className="inline-flex items-center gap-2 mt-8 text-violet-400 hover:text-violet-300 font-semibold transition">
          <ArrowLeft className="w-4 h-4" /> Back to Dashboard
        </Link>
      </div>
    );
  }

  const formattedDate = new Date(meeting.date).toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  }) + ' at ' + new Date(meeting.date).toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true
  });

  const transcriptLines = meeting.transcript.split('\n');
  const filteredTranscriptLines = transcriptLines.filter(line =>
    line.toLowerCase().includes(transcriptSearch.toLowerCase())
  );

  return (
    <div className="w-full flex flex-col space-y-6 animate-in fade-in duration-300">
      {/* Top Navbar */}
      <div className="flex items-center justify-between border-b border-zinc-900 pb-4">
        <Link href="/dashboard" className="inline-flex items-center gap-2 text-zinc-400 hover:text-zinc-200 font-medium transition text-sm">
          <ArrowLeft className="w-4 h-4" /> Back to Company Memory
        </Link>

        {meeting.status === 'completed' && (
          <button
            onClick={handleExportMarkdown}
            className="px-4 py-2 bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 rounded-xl text-xs font-semibold flex items-center gap-2 transition"
          >
            <Download className="w-4 h-4" /> Export Report (MD)
          </button>
        )}
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Side: Summary & Insights (7 columns) */}
        <div className="lg:col-span-7 space-y-6">
          {/* Header Metadata card */}
          <div className="glow-card p-6 border border-zinc-900">
            <span className="px-2.5 py-1 rounded-full bg-violet-500/10 text-violet-400 border border-violet-500/10 text-xs font-semibold uppercase tracking-wider">
              Meeting Summary & Action Dashboard
            </span>
            <h1 className="text-3xl font-extrabold font-display tracking-tight text-zinc-50 mt-4 leading-tight">
              {meeting.title}
            </h1>
            
            <div className="flex flex-wrap items-center gap-x-6 gap-y-3 mt-4 text-sm text-zinc-400">
              <div className="flex items-center gap-2">
                <Calendar className="w-4 h-4 text-zinc-500" />
                <span>{formattedDate}</span>
              </div>
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-zinc-500" />
                <span>{meeting.duration}</span>
              </div>
            </div>
          </div>

          {meeting.status === 'completed' && meeting.analysis ? (
            <>
              {/* Executive Summary */}
              <div className="glow-card p-6 border border-zinc-900">
                <h2 className="text-lg font-bold font-display text-zinc-100 flex items-center gap-2 mb-3">
                  <FileText className="w-5 h-5 text-violet-400" />
                  Executive Summary
                </h2>
                <p className="text-zinc-300 leading-relaxed text-sm">
                  {meeting.analysis.summary}
                </p>
              </div>

              {/* Insights Tab Box */}
              <div className="glow-card border border-zinc-900 overflow-hidden">
                {/* Tab buttons */}
                <div className="flex border-b border-zinc-900 bg-zinc-900/20">
                  <button
                    onClick={() => setActiveTab('decisions')}
                    className={`flex-1 py-4 text-sm font-semibold border-b-2 transition flex items-center justify-center gap-2 ${
                      activeTab === 'decisions' 
                        ? 'border-violet-500 text-violet-400 bg-violet-500/5' 
                        : 'border-transparent text-zinc-400 hover:text-zinc-300'
                    }`}
                  >
                    <span>Decisions</span>
                    <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${activeTab === 'decisions' ? 'bg-violet-500/20 text-violet-300' : 'bg-zinc-800 text-zinc-500'}`}>
                      {meeting.analysis.decisions.length}
                    </span>
                  </button>

                  <button
                    onClick={() => setActiveTab('actions')}
                    className={`flex-1 py-4 text-sm font-semibold border-b-2 transition flex items-center justify-center gap-2 ${
                      activeTab === 'actions' 
                        ? 'border-violet-500 text-violet-400 bg-violet-500/5' 
                        : 'border-transparent text-zinc-400 hover:text-zinc-300'
                    }`}
                  >
                    <span>Action Items</span>
                    <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${activeTab === 'actions' ? 'bg-violet-500/20 text-violet-300' : 'bg-zinc-800 text-zinc-500'}`}>
                      {meeting.analysis.actionItems.length}
                    </span>
                  </button>

                  <button
                    onClick={() => setActiveTab('risks')}
                    className={`flex-1 py-4 text-sm font-semibold border-b-2 transition flex items-center justify-center gap-2 ${
                      activeTab === 'risks' 
                        ? 'border-violet-500 text-violet-400 bg-violet-500/5' 
                        : 'border-transparent text-zinc-400 hover:text-zinc-300'
                    }`}
                  >
                    <span>Risks & Mitigations</span>
                    <span className={`px-2 py-0.5 rounded-full text-xs font-bold ${activeTab === 'risks' ? 'bg-violet-500/20 text-violet-300' : 'bg-zinc-800 text-zinc-500'}`}>
                      {meeting.analysis.risks.length}
                    </span>
                  </button>
                </div>

                {/* Tab content area */}
                <div className="p-6">
                  {/* Decisions Tab */}
                  {activeTab === 'decisions' && (
                    <div className="space-y-4">
                      {meeting.analysis.decisions.length === 0 ? (
                        <p className="text-sm text-zinc-500 text-center py-6">No key decisions identified in this sync.</p>
                      ) : (
                        meeting.analysis.decisions.map((d) => (
                          <div key={d.id} className="p-4 rounded-xl bg-zinc-950/40 border border-zinc-900 space-y-2.5">
                            <div className="flex items-start justify-between gap-3">
                              <h4 className="font-bold text-zinc-200 text-sm">{d.decision}</h4>
                              {d.decider && (
                                <span className="px-2.5 py-1 rounded-full bg-zinc-900 border border-zinc-800 text-zinc-400 text-xs font-medium shrink-0 flex items-center gap-1">
                                  <User className="w-3 h-3 text-zinc-500" />
                                  {d.decider}
                                </span>
                              )}
                            </div>
                            {d.context && (
                              <p className="text-zinc-400 text-xs leading-relaxed pl-1 border-l border-zinc-800">
                                <span className="text-zinc-500 uppercase tracking-wider font-semibold mr-1.5 text-[9px]">Context:</span>
                                {d.context}
                              </p>
                            )}
                          </div>
                        ))
                      )}
                    </div>
                  )}

                  {/* Action Items Tab */}
                  {activeTab === 'actions' && (
                    <div className="space-y-3">
                      {meeting.analysis.actionItems.length === 0 ? (
                        <p className="text-sm text-zinc-500 text-center py-6">No action items identified in this sync.</p>
                      ) : (
                        meeting.analysis.actionItems.map((a) => {
                          const isCompleted = a.status === 'completed';
                          return (
                            <div 
                              key={a.id} 
                              onClick={() => handleToggleAction(a.id)}
                              className={`p-4 rounded-xl border transition-all cursor-pointer flex items-start gap-4 select-none ${
                                isCompleted 
                                  ? 'bg-zinc-900/10 border-zinc-900 opacity-60' 
                                  : 'bg-zinc-950/50 border-zinc-900 hover:border-zinc-800'
                              }`}
                            >
                              <button className={`mt-0.5 shrink-0 transition ${isCompleted ? 'text-violet-400' : 'text-zinc-600'}`}>
                                {isCompleted ? (
                                  <CheckSquare2 className="w-5 h-5" />
                                ) : (
                                  <Square className="w-5 h-5" />
                                )}
                              </button>
                              
                              <div className="space-y-1.5">
                                <p className={`text-sm font-semibold leading-relaxed transition ${isCompleted ? 'line-through text-zinc-500' : 'text-zinc-200'}`}>
                                  {a.task}
                                </p>
                                <div className="flex flex-wrap items-center gap-x-4 gap-y-1.5 text-xs text-zinc-500">
                                  <span className="flex items-center gap-1.5 bg-zinc-900/50 border border-zinc-900 rounded-md px-2 py-0.5">
                                    <span className="font-semibold text-zinc-400">Owner:</span> {a.assignee}
                                  </span>
                                  {a.dueDate && (
                                    <span className="flex items-center gap-1.5 bg-zinc-900/50 border border-zinc-900 rounded-md px-2 py-0.5">
                                      <span className="font-semibold text-zinc-400">Due:</span> {a.dueDate}
                                    </span>
                                  )}
                                </div>
                              </div>
                            </div>
                          );
                        })
                      )}
                    </div>
                  )}

                  {/* Risks Tab */}
                  {activeTab === 'risks' && (
                    <div className="space-y-4">
                      {meeting.analysis.risks.length === 0 ? (
                        <p className="text-sm text-zinc-500 text-center py-6">No project risks detected in this sync.</p>
                      ) : (
                        meeting.analysis.risks.map((r) => {
                          const isHigh = r.impact === 'high';
                          const isMedium = r.impact === 'medium';
                          
                          return (
                            <div 
                              key={r.id} 
                              className={`p-4 rounded-xl border space-y-3 transition-all ${
                                isHigh 
                                  ? 'bg-rose-950/5 border-rose-900/20 shadow-md shadow-rose-950/5' 
                                  : isMedium 
                                    ? 'bg-amber-950/5 border-amber-900/10'
                                    : 'bg-zinc-950/40 border-zinc-900'
                              }`}
                            >
                              <div className="flex items-center justify-between gap-3">
                                <h4 className="font-bold text-zinc-200 text-sm flex items-center gap-2">
                                  {isHigh && <ShieldAlert className="w-4.5 h-4.5 text-rose-500 animate-pulse" />}
                                  {r.risk}
                                </h4>
                                <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider shrink-0 border ${
                                  isHigh 
                                    ? 'bg-rose-500/10 text-rose-400 border-rose-500/20' 
                                    : isMedium 
                                      ? 'bg-amber-500/10 text-amber-400 border-amber-500/20'
                                      : 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20'
                                }`}>
                                  {r.impact}
                                </span>
                              </div>
                              {r.mitigation && (
                                <div className="p-3 rounded-lg bg-zinc-950/80 border border-zinc-900/60 text-xs text-zinc-400 leading-relaxed">
                                  <span className="text-emerald-400 font-bold uppercase tracking-wide text-[9px] block mb-1">Mitigation Strategy:</span>
                                  {r.mitigation}
                                </div>
                              )}
                            </div>
                          );
                        })
                      )}
                    </div>
                  )}
                </div>
              </div>
            </>
          ) : (
            <div className="glow-card border-dashed border-zinc-800 p-12 text-center flex flex-col items-center justify-center">
              <AlertTriangle className="w-12 h-12 text-rose-400 mb-3" />
              <h3 className="text-lg font-bold text-zinc-300">Processing Pipeline Unfinished</h3>
              <p className="text-sm text-zinc-500 max-w-sm mt-1 mx-auto">
                {meeting.status === 'failed' 
                  ? `This meeting run failed during processing: ${meeting.error || 'Unknown error occurred'}`
                  : 'Wait a few moments, the transcription and insights generation is still running...'}
              </p>
            </div>
          )}
        </div>

        {/* Right Side: Interactive Transcript (5 columns) */}
        <div className="lg:col-span-5 flex flex-col h-[calc(100vh-270px)] min-h-[500px]">
          <div className="glow-card p-6 border border-zinc-900 flex-1 flex flex-col h-full overflow-hidden">
            {/* Transcript Title */}
            <div className="flex items-center justify-between pb-4 border-b border-zinc-900 mb-4 shrink-0">
              <h2 className="text-lg font-bold font-display text-zinc-100">
                Interactive Transcript
              </h2>
              {meeting.status === 'completed' && (
                <button
                  onClick={handleCopyTranscript}
                  className="px-2.5 py-1.5 rounded-lg text-xs font-semibold text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 flex items-center gap-1.5 transition active:scale-95"
                  title="Copy full transcript"
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-400" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      Copy Text
                    </>
                  )}
                </button>
              )}
            </div>

            {/* Transcript Search bar */}
            {meeting.status === 'completed' && (
              <div className="relative mb-4 shrink-0">
                <Search className="w-4 h-4 text-zinc-500 absolute left-3 top-1/2 -translate-y-1/2" />
                <input 
                  type="text" 
                  value={transcriptSearch}
                  onChange={(e) => setTranscriptSearch(e.target.value)}
                  placeholder="Filter dialogue text..."
                  className="w-full bg-zinc-950/60 border border-zinc-800 rounded-lg pl-9 pr-3 py-2 text-xs text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-zinc-700 transition"
                />
              </div>
            )}

            {/* Scrollable transcript area */}
            <div className="flex-1 overflow-y-auto pr-1 space-y-4 text-sm leading-relaxed scrollbar-thin">
              {meeting.status !== 'completed' ? (
                <div className="flex flex-col items-center justify-center h-full text-zinc-600 gap-2">
                  <div className="w-6 h-6 border border-zinc-700 border-t-zinc-400 rounded-full animate-spin" />
                  <p className="text-xs">Preparing transcript...</p>
                </div>
              ) : filteredTranscriptLines.length === 0 ? (
                <p className="text-zinc-500 text-center py-10 text-xs">No matching dialogue lines.</p>
              ) : (
                filteredTranscriptLines.map((line, idx) => {
                  const match = line.match(/^\[(\d{2}:\d{2})\]\s+([^(:]+)(?:\(([^)]+)\))?:\s*(.*)$/);
                  
                  if (match) {
                    const [, timestamp, speaker, role, speech] = match;
                    
                    return (
                      <div key={idx} className="p-3 rounded-lg bg-zinc-950/20 hover:bg-zinc-950/50 border border-transparent hover:border-zinc-900 transition-colors">
                        <div className="flex items-center justify-between mb-1">
                          <div className="flex items-center gap-1.5">
                            <span className="font-bold text-zinc-300 text-xs">{speaker.trim()}</span>
                            {role && (
                              <span className="text-[10px] text-zinc-500 bg-zinc-900 px-1.5 py-0.5 rounded border border-zinc-800">
                                {role.trim()}
                              </span>
                            )}
                          </div>
                          <span className="text-[10px] font-mono text-violet-400 bg-violet-950/20 border border-violet-900/10 px-1.5 py-0.5 rounded">
                            {timestamp}
                          </span>
                        </div>
                        <p className="text-zinc-300 text-xs">
                          {transcriptSearch ? (
                            (() => {
                              const regex = new RegExp(`(${transcriptSearch})`, 'gi');
                              const parts = speech.split(regex);
                              return parts.map((part, i) => 
                                regex.test(part) 
                                  ? <mark key={i} className="bg-violet-500/30 text-violet-200 px-0.5 rounded">{part}</mark>
                                  : part
                              );
                            })()
                          ) : (
                            speech
                          )}
                        </p>
                      </div>
                    );
                  }
                  
                  return (
                    <p key={idx} className="text-zinc-300 text-xs py-1 border-b border-zinc-900/30">
                      {line}
                    </p>
                  );
                })
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
